### PR TITLE
Allow support PHP 8.0

### PR DESCRIPTION
**Pull request by Yozhef**
## Changelog

```markdown
### Added
- Add support for PHP 8.x
```

### CODE REVIEW

**Comment by Yozhef** [comment]
Blocked. by https://github.com/sonata-project/SonataCacheBundle/pull/309

**Comment by jordisala1991** [comment]
Blocked because requires cache bundle v2 and that is not maintained anymore, compat for php8 is on cache-bundle v3.

One step could be try to add compat with v3 (dont know if that is possible because of type hints), the other way is to remove that integration and move to use symfony cache. This option will require next major tho.

wdyt @sonata-project/contributors

**Comment by phansys** [comment]
I'm a little confused about the status of `sonata-project/cache-bundle`. Is it deprecated or not? sonata-project/SonataCacheBundle#279.
BTW, I agree with the proposal of using `symfony/cache` as  replacement.

**Comment by VincentLanglet** [comment]
> I'm a little confused about the status of `sonata-project/cache-bundle`. Is it deprecated or not? [sonata-project/SonataCacheBundle#279](https://github.com/sonata-project/SonataCacheBundle/issues/279).

It's deprecated, but since some bundle are still using it, we're still maintaining it.

**Comment by wbloszyk** [comment]
> Blocked because requires cache bundle v2 and that is not maintained anymore, compat for php8 is on cache-bundle v3.
> 
> One step could be try to add compat with v3 (dont know if that is possible because of type hints), the other way is to remove that integration and move to use symfony cache. This option will require next major tho.
> 
> wdyt @sonata-project/contributors

IMO the best way will add PHP 8.0 support in cache-bundle v2. We can bump Symfony to ^4.0 too. Oher solution will require provide BC-break.

**Pull request closed without merging**
