### PR TITLE
Use the page name if the page has no SEO titel

### PR DESCRIPTION
**Pull request by core23**
Rebase of #420

### Changelog

```markdown
### Fixed
- The page name is now correctly used as a page title fallback
```

### Subject

The page name fallback could never be reached because of the surrounding if-statement.

### To do

- [X] Update the tests

### CODE REVIEW

**Comment by OskarStark** [comment]
@greg0ire `patch` is correct?

**Comment by core23** [comment]
IMO yes, because there is a logic that will use the page name, but a wrong if-statement makes it unreachable.

**Comment by greg0ire** [comment]
Kein deutsch bitte! "titel" => "title"

**Comment by greg0ire** [comment]
Well I'll fix that with squash merge

**Comment by greg0ire** [comment]
Here you go! Danke schön @core23 !

**Comment by jaxel87** [comment]
This commit breaks seo bundle functionality. Now I can't set  Seo Title values at runtime. Sonata Page Title always replace them.
`$seoPage = $this->container->get('sonata.seo.page');

$seoPage->setTitle($post->getTitle())`

**Comment by core23** [comment]
Can you please show a little bit more of your code?

**Comment by OskarStark** [comment]
@core23 do we have a test for this?

**Comment by Soullivaneuh** [comment]
Maybe adding `is_null($this->seoPage->getTitle())` to the condition will solve the issue? Didn't test.

**Comment by jaxel87** [comment]
$seoPage->setTitle($title) called 3 times. First set titile from config. Second - at runtime. Third - if page have title in admin. SeoPage Title should not be overwritte, if $page->getTitle() is null.

`        if ($page->getTitle()) {
            $this->seoPage->setTitle($page->getTitle());
        }

        if (!$this->seoPage->getTitle()) {
            $this->seoPage->setTitle($page->getName());
        }
`

**Comment by core23** [comment]
IMHO this is another issue.

The title was always overwritten, the only thing that was changed is the fallback to the page name. Maybe you didn't have a page title, so your code just works before the patch.

**Pull request merged**
