### PR TITLE
Fix issue with block removing

### PR DESCRIPTION
**Pull request by qsomazzi**

### CODE REVIEW

**Comment by qsomazzi** [comment]
ping @rande

**Comment by OskarStark** [comment]
@core23 can you verify this PR?

@qsomazzi what is the exact problem?

**Comment by qsomazzi** [comment]
The problem is that sometimes, when I remove a block, the background-layer of the modal stay, and the modal fade properly. So I can't use the website anymore, we need to remove the backdrop to use the app again. My PR is just a fix to prevent this when it's appear.

**Comment by qsomazzi** [comment]
see with @rande

**Pull request merged**
