### PR TITLE
Fix broken 2.3 build

### LINKED ISSUE #614: Branch 2.3 is broken
Maybe we need a backport?

### PR DESCRIPTION
**Pull request by greg0ire**
- quote string with meta characters
- replace # with // in javascript code snippet

Conflicts:
	Resources/doc/reference/api.rst

Fixes #614

### CODE REVIEW

**Comment by greg0ire** [comment]
Found the commit by @qsomazzi

**Comment by qsomazzi** [comment]
Hello @greg0ire I think you have to rebase your PR to have only your commits.

**Comment by greg0ire** [comment]
Hello @qsomazzi and sorry, but you're thinking wrong. I deliberately reused your commit from master on the 2.3 branch, because why would I rewrite it myself? It works! See this PR as a collaborative work :)

**Comment by Th3Mouk** [comment]
:+1 ggwp

**Comment by greg0ire** [comment]
Thanks :) @core23 @OskarStark merge plz

**Comment by qsomazzi** [comment]
ok then :) :+1:

**Comment by OskarStark** [comment]
thank you @greg0ire @qsomazzi

**Pull request merged**
