### PR TITLE
Page-Composer: removes custom status-code check (relying on Response-Status instead)

### PR DESCRIPTION
**Pull request by mvhirsch**
I am targeting this branch, because of an introduced update of sonata-project/admin-bundle which should be synchronized in page-bundle too.

Fixes bug resulted in change of https://github.com/sonata-project/SonataAdminBundle/pull/4449

## Changelog

```markdown
### Fixed
- Composer (JS): Relying of custom status-property; instead rely on Response Status Code
```

## TODO

- [x] Update sonata-page.back.js
- [x] Generate minified version of sonata-page.back.js

## Subject

After updating to SonataAdminBundle 3.17 (or higher) the composer broke.
Reading this PR https://github.com/sonata-project/SonataAdminBundle/pull/4449#issuecomment-298901450 I saw a non-BC-change which should be updated in SonataPageBundle too.
So I removed the necessity to check the body's status-property. Now only the Response-Status-Code is used to determine success/fail.

I just don't have any clue about how you guys generate the minified version of this JS?

### CODE REVIEW

**Comment by greg0ire** [comment]
> I just don't have any clue about how you guys generate the minified version of this JS?

@qsomazzi @core23 @plouc @meyerbaptiste do you know how this is usually done? Also, do you know why minified files have the executable bit set 😕 ?

**Comment by mvhirsch** [comment]
Maybe just being pedantic at this but: why is the header-comment included twice in both (back.js & front.js) files?

**Comment by greg0ire** [comment]
Also: why is the first header saying the file is generated ?

**Comment by greg0ire** [comment]
Or is the header generated?

**Comment by greg0ire** [comment]
Best way to find out which is right might be to remove both and let StyleCI or whatever re add them

**Comment by greg0ire** [comment]
Hmmm, it looks like StyleCI just doesn't care about JS files, which makes sense... sorry for the trouble.

**Comment by mvhirsch** [comment]
> Hmmm, it looks like StyleCI just doesn't care about JS files, which makes sense... sorry for the trouble.

Nevermind :-)
Anyway, should I revert the commit or do we remove the comment anyway?

**Comment by greg0ire** [comment]
I think we should remove one of them. Can you look at other sonata bundles?

**Comment by mvhirsch** [comment]
> I think we should remove one of them. Can you look at other sonata bundles?

I've taken a look at PHP-files and cross-checked with another [JS-file: SonataAdminBundle's Admin.js](https://github.com/sonata-project/SonataAdminBundle/blob/3.x/Resources/public/Admin.js). 
So this should be fine now :-)

Left open: how to minify? Should I throw it against [Googles online JS compiler](https://closure-compiler.appspot.com/home)?

**Comment by greg0ire** [comment]
> Left open: how to minify? Should I throw it against Googles online JS compiler?

Yes, please try that, it should be ok, I guess...

**Comment by greg0ire** [comment]
Please kindly squash your commits together. If you don't, we'll try to remember to do it for you but it's best if you save us this trouble.

How to do that?

1. `git rebase -i origin/3.x`, assuming `origin` is a git remote that points to this repository, and not your fork. If you're not sure what your remotes are, run `git remote -vvv`, there should be your fork and the holy/reference/base/origin/whatever-you-call-it repository.
2. A window will show up with many lines, replace `pick` with `fixup` on every line but the first one
3. Close your editor, git should do its magic, and you should end up with one commit
4. Use `git push --force` to overwrite what you already pushed. Don't forget the `--force` option otherwise git will try to merge both things together.

**Comment by mvhirsch** [comment]
@greg0ire I squashed it :-)

**Comment by greg0ire** [comment]
@sonata-project/contributors please review

**Comment by greg0ire** [comment]
Thanks @mvhirsch

**Pull request merged**
