### PR TITLE
Make REST dependency optional

### PR DESCRIPTION
**Pull request by core23**

### CODE REVIEW

**Comment by OskarStark** [comment]
@core23 please add some infos to the docs, thank you :+1:

**Comment by core23** [comment]
Done.

There is an build error in ``https://github.com/sonata-project/SonataPageBundle/blob/master/Resources/doc/reference/api.rst``. Can you have a look @OskarStark ? I am not so good with RST.

**Comment by OskarStark** [comment]
hmm, but this file is not related to this PR..

**Comment by OskarStark** [comment]
Lets check my change here: #602

**Pull request merged**
