### PR TITLE
Fix exception list template overwriting wrong block

### PR DESCRIPTION
**Pull request by Neodork**
See https://github.com/sonata-project/SonataPageBundle/issues/592

### CODE REVIEW

**Comment by OskarStark** [comment]
Is this correct @rande ?

**Comment by OskarStark** [comment]
ping @core23

**Comment by core23** [comment]
Looks okay to me

**Comment by greg0ire** [comment]
@Neodork : can you please rebase on the tip of master?

**Comment by core23** [comment]
Wait... :-1: for this. There is no block named ``body``.

**Comment by Neodork** [comment]
@greg0ire Yes, I will rebase this to master next week (monday). Been very busy with deadlines.

**Comment by Neodork** [comment]
ping @greg0ire

**Comment by greg0ire** [comment]
Tests are passing. Good to merge.

**Comment by core23** [comment]
Thank you @Neodork

**Pull request merged**
