### PR TITLE
Travis and CS master backport

### PR DESCRIPTION
**Pull request by Soullivaneuh**

### CODE REVIEW

**Comment by rande** [comment]
Ouch!

**Comment by Soullivaneuh** [comment]
Ouch?

**Comment by Soullivaneuh** [comment]
@rande Again the iconv issue: https://travis-ci.org/sonata-project/SonataPageBundle/jobs/78742302#L394

Can you remember me how did you solve it?

**Comment by rande** [comment]
@Soullivaneuh we need to adjust the locale in the test as sf2.7 force the locale before starting the test.

**Comment by Soullivaneuh** [comment]
This was already done on master AFAIK. Can you give me the related commit?

**Comment by rande** [comment]
https://github.com/sonata-project/SonataPageBundle/commit/317333b7f19046ae186a0a9837851752e3a84f5c

**Pull request merged**
