### PR TITLE
replace deprectaed bind form method

### PR DESCRIPTION
**Pull request by amine2z**
fix deprecation of bind method from FormInterface

### CODE REVIEW

**Comment by OskarStark** [comment]
ping @rande

**Comment by OskarStark** [comment]
@amine2z could you please fix the typo in your commit message and please rebase as the master branch is passing the travis build, maybe we changed some configuration.

thank you

@core23 please have a second look, but IMO we can merge this

**Comment by core23** [comment]
Looks fine, except the commit message / PR title ;)

**Comment by OskarStark** [comment]
Thank you, i changed the merge commit message :+1:

**Pull request merged**
