### PR TITLE
cascade persist for block parent

### PR DESCRIPTION
**Pull request by Vesax**
I am targetting this branch, because this is a non-BC fix

## Changelog

``` markdown
### Fixed
- missing cascade persistence for parent block.
```
## Subject

For now, we can't create block with its new parent, besause cascade persistence not enabled.
But it is enabled for page's parent.
(For example, it is very important feature for moving pages from another cms solution).

### CODE REVIEW

**Comment by Vesax** [comment]
@OskarStark What do you think about it?

**Comment by OskarStark** [comment]
to be honest, I#m not that deep in this topic

maybe @core23 can help!

**Comment by core23** [comment]
Not sure, if we need this. Can you can name where the cascade persist is needed in this bundle?

When creating a new block, the parent block is already persisted. We need the cascade persist only when creating a cascaded tree, which is not the case in this bundle.

**Comment by OskarStark** [comment]
Ping @Vesax

**Comment by core23** [comment]
Please give an example why we need this fix or close this PR @Vesax

**Pull request closed without merging**
