### PR TITLE
add support for cocur/slugify 2.x

### PR DESCRIPTION
**Pull request by OskarStark**
### Changelog

```markdown
### Added
- Support version 2.x for `cocur/slugify` dependency
```

### Subject

Support `cocur/slugify` 2.x

SonataCoreBundle already supports it: https://github.com/sonata-project/SonataCoreBundle/blob/3.x/composer.json#L27

### CODE REVIEW

**Comment by OskarStark** [comment]
Lets try it, but i think this isn't working, until we drop Support for PHP 5.3...

From the Changelog:
> #97 Set minimum PHP version to 5.5.9 (by florianeckerstorfer)

**Comment by OskarStark** [comment]
i could resubmit this against `master` and adjust the minimum php version

**Comment by Soullivaneuh** [comment]
> Lets try it, but i think this isn't working, until we drop Support for PHP 5.3...

Then composer will fallback to `cocur/slugify` 1.x. What is the problem if we support both?

**Comment by Soullivaneuh** [comment]
Could you check and confirm that code using `cocur/slugify` is tested? If not, could you please fix this?

**Comment by OskarStark** [comment]
> Then composer will fallback to cocur/slugify 1.x. What is the problem if we support both?

you are right, i am already a bit tired 😄

**Comment by OskarStark** [comment]
> Could you check and confirm that code using cocur/slugify is tested? If not, could you please fix this?

Will do this

**Comment by OskarStark** [comment]
We have tests: https://github.com/sonata-project/SonataPageBundle/blob/3.x/Tests/Model/PageTest.php#L18

**Comment by Soullivaneuh** [comment]
Great, RTM so.

**Comment by Soullivaneuh** [comment]
https://github.com/sonata-project/SonataPageBundle/blob/3.0.1/SonataPageBundle.php#L65

Would be great to have a deprecation warning here.

**Comment by OskarStark** [comment]
> Would be great to have a deprecation warning here.

done in #673

**Pull request merged**
