### PR TITLE
Modernise frontend code

### PR DESCRIPTION
**Pull request by jordisala1991**
## Subject

I am targeting this branch, because this is BC break.

## Changelog

```markdown
### Changed
- Change frontend compilation system from Gulp to Webpack
- Change final minified file to `app.js` and `app.css`
```

### CODE REVIEW

**Comment by jordisala1991** [comment]
Your latest PR on admin bundle might have break some builds @VincentLanglet

**Comment by VincentLanglet** [comment]
> Your latest PR on admin bundle might have break some builds @VincentLanglet

I'm using the modelManager in some methods now, so if it's not set in unit test it will fail indeed.

**Comment by VincentLanglet** [comment]
https://github.com/sonata-project/SonataPageBundle/pull/1560

**Comment by jordisala1991** [comment]
Two things fixed here (besides the full migrations and upgrade of the code to be a little better):

* Composer page now kinda works (not it does not fail on the js part, but rather when saving blocks on the PHP part, to see on another PR)
* Layout is a bit better on Sonata, before it was a bit broken on some parts.

cc @eerison

**Review by VincentLanglet — APPROVED** [review]

**Comment by VincentLanglet** [comment]
Nice job

**Pull request merged**
