### PR TITLE
call checkAccess() on admin class instead of $this

### PR DESCRIPTION
**Pull request by FabienD**
Hi,

Just a little PR to fix a bug introduces by #534 when you try to create a page snapshot.

Fabien

### CODE REVIEW

**Comment by OskarStark** [comment]
can you please make a better commit message @FabienD ?

after that we can merge this PR

thank you

**Comment by FabienD** [comment]
I've updated the commit message, it's more relevant ?

**Comment by OskarStark** [comment]
can you please change the headline of this issue and the commit message to:

```call checkAccess() on admin class instead of $this````

thank you

**Comment by FabienD** [comment]
It's updated.
Thx

**Comment by OskarStark** [comment]
Thank you @FabienD

**Pull request merged**
