### PR TITLE
fix command sonata:page:clone-site

### LINKED ISSUE #827: command sonata:page:clone-site doesn't work
in Comand line when we use 

> sonata:page:clone-site --help

on input we have:

`[Symfony\Component\Console\Exception\LogicException]  
  An option with shortcut "s" already exists.           
                                                        

help [--xml] [--format FORMAT] [--raw] [-h|--help] [-q|--quiet] [-v|vv|vvv|--verbose] [-V|--version] [--ansi] [--no-ansi] [-n|--no-interaction] [-s|--shell] [--process-isolation] [-e|--env ENV] [--no-debug] [--] <command> [<command_name>]`

### PR DESCRIPTION
**Pull request by Migo2468**
Command sonata:page:clone-site doesn't work because shortcut "s" is reservation in "shell"

Closes #827

## Fixed
- fix sonata-project/SonataPageBundle#827 work command sonata:page:clone-site, change source-id shortcut

### Changed
In file /Command/CloneSiteCommand.php line 37

### CODE REVIEW

**Comment by Migo2468** [comment]
I think so.

**Comment by greg0ire** [comment]
1. Fetch all new commits: `git fetch --all`. ⬇️ 
2. Rebase on what you fetched interactively: ✂️ 
    1. `git rebase -i origin/3.x`, assuming `origin` is a git remote that points to this repository, and not your fork. If you're not sure what your remotes are, run `git remote -vvv`, there should be your fork and the holy/reference/base/origin repository.
    2. A window will show up with many lines, remove every line but the last one, which should correspond to your commit.
   2. If you run into a conflict: 💥 
        1. fix it with `git mergetool`. 😷 
        1. continue on your merry way with `git rebase --continue`. ⏩ 
3. Force push to overwrite all this : `git push --force`. ⬆️

**Comment by Migo2468** [comment]
In test we don't have any command with shortcut. 
In documentation we don't have this command with shortcut. 

**It's everything.**

**Comment by greg0ire** [comment]
@Migo2468 where is your commit?

**Comment by Migo2468** [comment]
Here https://github.com/Migo2468/SonataPageBundle/commit/dba9a71187064b2c1890b06ca8206756bf5d38b4

**Comment by Migo2468** [comment]
Sorry I clone repo and commit in my I have not noticed

**Comment by greg0ire** [comment]
Oh right.

**Comment by greg0ire** [comment]
Please create a PR from your fork to our origin ;)

**Comment by greg0ire** [comment]
Like this @Migo2468 https://github.com/sonata-project/SonataPageBundle/compare/3.x...Migo2468:patch-1

**Pull request closed without merging**
