### PR TITLE
Drop SonataCoreBundle

### PR DESCRIPTION
**Pull request by wbloszyk**
## Subject

I am targeting this branch, because it its BC-break.

## Changelog

```markdown
### Removed
- Removed `SonataCoreBundle` 
```

### CODE REVIEW

**Comment by greg0ire** [comment]
Trying to get a report from Travis…

**Comment by phansys** [comment]
> Trying to get a report from Travis…

Round 2...

**Comment by greg0ire** [comment]
The Travis build failed, please look into it.

**Comment by core23** [comment]
Can we do this on the stable now? @wbloszyk

**Comment by wbloszyk** [comment]
I think better finish https://github.com/sonata-project/dev-kit/issues/697 and them merge it from 3.x
@greg0ire WDYT?

**Comment by wbloszyk** [comment]
Closing this in favor of #1156

**Pull request closed without merging**
