### PR TITLE
allow jms/serializer 1.0 stable

### LINKED ISSUE #522: dev-master -> JMS serializer Problem
bildschirmfoto 2015-09-02 um 18 01 35

@Soullivaneuh can we use the 1.0 here?
or is there a problem?

bildschirmfoto 2015-09-02 um 18 02 55

cc @rande

### PR DESCRIPTION
**Pull request by OskarStark**
Fixes #522 
Fixes #523

### CODE REVIEW

**Comment by OskarStark** [comment]
@Soullivaneuh looks like the travis error is unrelated!

**Comment by OskarStark** [comment]
ping @rande

**Comment by OskarStark** [comment]
ping @Soullivaneuh

**Comment by rande** [comment]
Tests are failing. Can you try to rebase this PR to get the latest changes, seems to break with CS conventions.

**Comment by Soullivaneuh** [comment]
@OskarStark CS fixed in 4847410ae904ef49c48782e464953c1f466bf24c, please rebase your PR.

**Comment by OskarStark** [comment]
done @Soullivaneuh

**Comment by Soullivaneuh** [comment]
Thank you @OskarStark

**Comment by OskarStark** [comment]
thank you @Soullivaneuh

**Pull request merged**
