### PR TITLE
Change default entity class values

### PR DESCRIPTION
**Pull request by eerison**
## Subject

I am targeting this branch, because {reason}.

Closes #{put_issue_number_here}.

## Changelog

```markdown
### Added
- Added some `Class::newMethod()` to do great stuff.

### Changed

### Deprecated

### Removed

### Fixed

### Security
```

### CODE REVIEW

**Comment by eerison** [comment]
Hey @jordisala1991 do you have any idea why do we need this : https://github.com/sonata-project/SonataPageBundle/blame/4.x/src/DependencyInjection/SonataPageExtension.php#L266

in theory sonata page bundle works without it

**Comment by VincentLanglet** [comment]
Should we just remove the default values since we don't provide entities ?

**Comment by jordisala1991** [comment]
I think we should do the same like the other bundles (we didnt remove the default values)

**Comment by VincentLanglet** [comment]
> I think we should do the same like the other bundles (we didnt remove the default values)

Like this then https://github.com/sonata-project/SonataPageBundle/pull/1635 ?
Seems like tests are failing

**Pull request closed without merging**
