### PR TITLE
Re-allow SF DI>4.4.0 & upgrade di test package

### PR DESCRIPTION
**Pull request by bmaziere**
## Subject
I am targeting this branch, because it does not contain BC break i guess.

to understand this: 
- https://github.com/symfony/dependency-injection/commit/ddb02286fb427dc6aba02cabc150f21b40aeb349
- https://github.com/SymfonyTest/SymfonyDependencyInjectionTest/commit/3431fc928541fa676a88cf59adb4bc45dbcc6764

## Changelog

```markdown
### Changed
- Re-allow SF DI>4.4.0
- Upgrade matthiasnoback/symfony-dependency-injection-test to ^4.0
```

### CODE REVIEW

**Comment by greg0ire** [comment]
If you want to use the latest di test package, you will have to upgrade phpunit to version 8 (can be done in `.travis.yml`. If that works, we will have to do a dev-kit PR.

**Comment by greg0ire** [comment]
You will have to add `:void` to all `setUp` and `tearDown` methods if you want this to work.

**Comment by bmaziere** [comment]
not sure but according to the build i guess i need to open a PR on CoreBundle

**Comment by bmaziere** [comment]
waiting for https://github.com/sonata-project/SonataCoreBundle/pull/729 to be merged :)

**Comment by core23** [comment]
> waiting for [sonata-project/SonataCoreBundle#729](https://github.com/sonata-project/SonataCoreBundle/pull/729) to be merged :)

The CoreBundle is deprecated, please try to port the breaking code to this bundle

**Comment by bmaziere** [comment]
@core23 don't think there is any breaking code to port here. Build is just failing because of CoreBundle or am I miss understanding?

**Comment by greg0ire** [comment]
@core23 is saying you should just copy the `XliffValidatorTestCase` to the page bundle if I understand correctly.

**Comment by bmaziere** [comment]
almost understood. However, even with migrating all tests from CoreBundle to PageBundle (because some others will make the build fail), without merging anything in CoreBundle it will still fail. Or do we need to merge the removal of all test inside CoreBundle first? Not sure of what i have to do here sorry 😬

**Comment by greg0ire** [comment]
`XliffTest` should no longer extend the class from the core bundle I think. You can copy all necesseary method from `XliffValidatorTestCase` to it. That will remove the dependency to the core bundle for tests.

> because some others will make the build fail

Some other tests? Which ones?

**Comment by bmaziere** [comment]
sorry i miss understood the core bundle relationship in the test 😬 hope i did what was expected ;)

**Comment by greg0ire** [comment]
I created a PR on dev-kit to make sure we stay with PHPUnit 8: https://github.com/sonata-project/dev-kit/pull/541

Also, I'm going to release a new version of the page bundle

**Pull request merged**
