### PR TITLE
Failed to create object: AppBundle\Entity\Site 

### PR DESCRIPTION
**Pull request by symfou**
[2/4] PDOException: SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'host' cannot be null

### CODE REVIEW

**Comment by OskarStark** [comment]
@rande what do you think?

Oskar

**Comment by core23** [comment]
:+1:

**Comment by Soullivaneuh** [comment]
According to the new [Sonata version management](https://github.com/sonata-project/SonataAdminBundle/issues/3053) and next major [release plan](https://github.com/sonata-project/SonataAdminBundle/issues/3731), this project has been refactored regarding branching and versioning.

If you see this message, your PR concerns a patch or a minor release and is not targeting the right branch.

So I'm closing this one, but don't see it as a refusal. If you think your work is still relevant and want to continue, feel free to reopen it on the right branch (e.g. the default one).

Regards.

**Comment by OskarStark** [comment]
@symfou can you please resubmit this again to `3.x` ?

**Pull request closed without merging**
