### PR TITLE
update Dutch translations

### PR DESCRIPTION
**Pull request by zghosts**
Updates the Dutch translations

I am targeting this branch, because it only updates translations

## Changelog
Update Dutch translations

### CODE REVIEW

**Review by core23 — APPROVED** [review]

**Comment by VincentLanglet** [comment]
Same than here: https://github.com/sonata-project/SonataMediaBundle/pull/1853#discussion_r515529954

I'm not sure about the xlf part.
Since you're the one who added them: https://github.com/sonata-project/SonataPageBundle/commit/e68286f48adcfffae56960285e5764973b7bbd4a maybe you can explain why a xlf file instead of the xliff one @core23 ? :)

**Comment by OskarStark** [comment]
It should be renamed to xliff

**Review by VincentLanglet — APPROVED** [review]

**Comment by zghosts** [comment]
Changed.
On a sidenote, can you keep the hacktoberfest label on the repositories, or label PR's done during hacktoberfest as "hacktoberfest_accepted" since it seems they are longer counted.

**Comment by VincentLanglet** [comment]
Hi @zghosts Can you fix the test

Thanks :)

**Comment by OskarStark** [comment]
Can you please rebase on `3.x`? And check a last xml error?

**Comment by zghosts** [comment]
That should do it, pending tests

**Pull request merged**
