### PR TITLE
#828

### PR DESCRIPTION
**Pull request by Migo2468**
change "s" to "so" because "s" open shell console

Closes #828 

## Changelog

```markdown
### Fixed
- crash when running `sonata:page:clone-site`

```

### CODE REVIEW

**Comment by Migo2468** [comment]
It is ok?

**Comment by Migo2468** [comment]
Sorry for the confusion. Thank you for help.

**Comment by greg0ire** [comment]
No problem, thanks for contributing this fix.

**Comment by greg0ire** [comment]
Congrats on your first contribution @Migo2468 !

**Comment by OskarStark** [comment]
Released here in tag [3.5.1](https://github.com/sonata-project/SonataPageBundle/releases/tag/3.5.1)

**Pull request merged**
