### PR TITLE
Added sf4 to composer.json.

### PR DESCRIPTION
**Pull request by mmaarriiuuss**
I am targeting this branch, because this is BC.

## Changelog

```markdown
### Added
- compatibility for Symfony 4.0
```

#SymfonyConHackday2017

### CODE REVIEW

**Comment by greg0ire** [comment]
The tests are still failing: https://travis-ci.org/sonata-project/SonataPageBundle/jobs/303973639

**Comment by OskarStark** [comment]
@mmaarriiuuss I removed the dependency and fixed the PR header.

If tests are green, please squash merge this PR @sonata-project/contributors

**Comment by greg0ire** [comment]
I'm afraid we are not compatible with sf4 yet, because of this huge bug: https://github.com/sonata-project/SonataAdminBundle/issues/4701

**Comment by jordisala1991** [comment]
Ping @mmaarriiuuss , can you rebase?

**Comment by jordisala1991** [comment]
Will be fixed in #923

**Pull request closed without merging**
