### PR TITLE
[ADD] allow hybrid pages to be root on the hierarchy

### PR DESCRIPTION
**Pull request by juanolon**
This changes where made for the version 2.3. I think, they should also be compatible with master. but i cannot test it. currently only using 2.3

### CODE REVIEW

**Comment by OskarStark** [comment]
@juanolon can you please provide a Test for this feature?

Thank you! :+1:

**Comment by OskarStark** [comment]
ping @juanolon

**Comment by juanolon** [comment]
hi @OskarStark sorry didn't answer, but have no time at the moment. also, i'm not so familiar writing tests, so it would take me a little more time for doing it..

**Comment by OskarStark** [comment]
no problem @juanolon

**Comment by OskarStark** [comment]
if you rebase your PR and execute ``make cs`` travis will be happy :+1:

**Comment by greg0ire** [comment]
@Soullivaneuh why did you close this?

**Comment by moshenskyDV** [comment]
Ping. This solution worked for me!!
@Soullivaneuh  @greg0ire anyone, can approve this request?

**Comment by greg0ire** [comment]
@moshenskyDV you can create your own PR from this one, because approving will not be enough (there are some cs issues apparently)

**Pull request closed without merging**
