### PR TITLE
Update old symfony_cmf_routing_extra mention to new cmf_routing

### PR DESCRIPTION
**Pull request by jasperdcbe**
I think this part of the documentation was not updated yet. It's mentioned correctly in the configuration: http://sonata-project.org/bundles/page/master/doc/reference/installation.html#configuration

### CODE REVIEW

**Comment by OskarStark** [comment]
This is correct @jasperdcbe :+1: 

Would you like to rebase your PR that i can merge it?

Oskar

**Comment by OskarStark** [comment]
ping @jasperdcbe

**Comment by core23** [comment]
Please rebase @jasperdcbe

**Comment by Soullivaneuh** [comment]
According to the new [Sonata version management](https://github.com/sonata-project/SonataAdminBundle/issues/3053) and next major [release plan](https://github.com/sonata-project/SonataAdminBundle/issues/3731), this project has been refactored regarding branching and versioning.

If you see this message, your PR concerns a patch or a minor release and is not targeting the right branch.

So I'm closing this one, but don't see it as a refusal. If you think your work is still relevant and want to continue, feel free to reopen it on the right branch (e.g. the default one).

Regards.

**Pull request closed without merging**
