### PR TITLE
SF 4+ support

### LINKED ISSUE #1410: Symfony 5 and 6 support
## Feature Request

The bundle does not currently support recent versions of Symfony. Symfony 4 will not be maintained anymore in November. Is there a plan to make this bundle compatible with recent versions?

### PR DESCRIPTION
**Pull request by Haniki**
## WIP Upgrade SonataPageBundle for symfony4 +

I tried to make this bundle compatible with symfony 4+ . It still misses a lot of things but I won't have time to finish this.
I don't know if this can help or not but I put it there anyways since I saw this topic still open : https://github.com/sonata-project/SonataPageBundle/issues/1410#issuecomment-1104855589.

I am targeting this branch, because it cannot be done without a BC-break.

Closes #1410.

## Changelog

```markdown

### Changed
- Bumped versions in composer to use SonataAdmin 4 and SonataBlock 4

### Removed
- Removed Deprecated blocks

```

## To do

- [ ] Update the tests;
- [ ] Update the documentation;
- [ ] Add an upgrade note.
- [ ] Check compatibility with media bundle widgets.

### CODE REVIEW

**Comment by eerison** [comment]
@Haniki 

do you think that is possible create a Pull request smaller?

for example do not remove deprecated code in this PR, just things that are really necessary to change to support symfony 5/6

**Comment by eerison** [comment]
@Haniki 

do you think that is possible create a Pull request smaller?

for example do not remove deprecated code in this PR, just things that are really necessary to change to support symfony 5/6

**Comment by eerison** [comment]
as this Pull request is not able to review yet, maybe you could put this as `DRAFT`?

**Comment by Hanmac** [comment]
sorry i didn't noticed that some of the changes i did in smaller PRs you did in this one too.

@Haniki 
one question i have, i made a PR for Twig PageExtendion , but why did you remove `sonata_page_breadcrumb`? was it deprecated or something?

**Comment by Haniki** [comment]
To be honest I don't really remember ... I just tried to make the bundle work for me, and pushed my code here if it could help in any ways.

**Comment by VincentLanglet** [comment]
I will close this since we already started in multiple smaller PR. Smaller steps are easier to review.
But thanks for the help.

**Pull request closed without merging**
