### PR TITLE
Applied fixes from StyleCI

### PR DESCRIPTION
**Pull request by greg0ire**
This pull request applies code style fixes from an analysis carried out by [StyleCI](https://styleci.io).

---

For more information, click [here](https://styleci.io/analyses/z3GRJG).

### CODE REVIEW

**Comment by OskarStark** [comment]
can be deleted imo @greg0ire

**Comment by greg0ire** [comment]
Why? Isn't it a good change?

**Comment by OskarStark** [comment]
because @Soullivaneuh is doing this via dev-kit I think, he closed all my auto created PR's from Style CI

ping @Soullivaneuh

**Comment by Soullivaneuh** [comment]
> he closed all my auto created PR's from Style CI

Wait, what? Oo

BTW, this change should be applied.

**Comment by greg0ire** [comment]
> BTW, this change should be applied.

And maybe some others @OskarStark , didn't you close other PRs like this one?

**Comment by Soullivaneuh** [comment]
If you closed a PR like this, it will reappear after the next commit of the concerned branch.

**Comment by OskarStark** [comment]
> And maybe some others @OskarStark , didn't you close other PRs like this one?

no, @Soullivaneuh closed a few ones like this, i saw them

**Comment by greg0ire** [comment]
OK… anyway, no big deal, since he fixes will reappear

**Pull request merged**
