### PR TITLE
Addition to Doc

### PR DESCRIPTION
**Pull request by stphnpt**
## Subject

Details the block services provided by the bundle

### CODE REVIEW

**Comment by greg0ire** [comment]
Would you use "addition to code", as a commit message? If not, why do you think this would be ok for documentation ?

**Comment by Soullivaneuh** [comment]
@stphnpt I changed your commit message.

Please take a look: https://github.com/sonata-project/SonataPageBundle/commit/686e99a57bb2d2057b2c8e04cf0cddda567c257b

Thanks for your contribution.

**Comment by greg0ire** [comment]
Anyway, thanks for your contribution @stphnpt !

**Comment by stphnpt** [comment]
@greg0ire 56 chars ... but much better for sure !

**Comment by greg0ire** [comment]
> 56 chars

@Soullivaneuh ಠ_ಠ , didn't github tell you about that ?

**Comment by OskarStark** [comment]
> @Soullivaneuh ಠ_ಠ didn't github tell you about that ?

it doesn't

**Comment by greg0ire** [comment]
> it doesn't

Strange, it does for commit messages, but not for squash/merge messages then.

**Comment by OskarStark** [comment]
bildschirmfoto 2016-06-21 um 13 55 48

**Comment by Soullivaneuh** [comment]
50 chars is a **recommendation**, not an obligation.

The goal is to not have a commit message truncated because of a too long sentence.

And this is not the case.

But yes, it's weird to show the recommendation on the commit part but not the merge part.

**Pull request merged**
