### PR TITLE
Support php 8

### PR DESCRIPTION
**Pull request by 4c0n**
## Subject

Support php 8

I am targeting this branch, because I need the current version to support PHP 8.

## Changelog

Support PHP 8.

### CODE REVIEW

**Comment by VincentLanglet** [comment]
The sonata-project/cache-bundle need to support PHP8 first

**Comment by 4c0n** [comment]
@VincentLanglet Actually it seems that it already does: https://github.com/sonata-project/SonataCacheBundle/blob/d0b13b4dcc85272f2235e7fbd50578dd403222b0/composer.json#L22

However this bundle should support the newer version of that bundle:
https://github.com/sonata-project/SonataPageBundle/blob/fed26c06856de8d6b1161d0f23001db7b8377e2b/composer.json#L31

**Comment by VincentLanglet** [comment]
Oh yes indeed, it required the sonata-project/cache-bundle 3.
Another option is to stop using the cache bundle, since it's deprecated.

https://github.com/sonata-project/SonataPageBundle/issues/1096
https://github.com/sonata-project/SonataCacheBundle/issues/279

**Comment by 4c0n** [comment]
@VincentLanglet Is that not a BC break? I'd rather remove it to be honest, but I guess it should be replaced with some integration of the standard Symfony cache support?

**Comment by VincentLanglet** [comment]
> @VincentLanglet Is that not a BC break? I'd rather remove it to be honest, but I guess it should be replaced with some integration of the standard Symfony cache support?

It depends how it's done, but I'm not sure. I know nothing about this bundle.

Another easy option could be to add support for php8 to the cache bundle v2.

**Comment by 4c0n** [comment]
@VincentLanglet turns out it wasn't too hard to use version 3: https://github.com/sonata-project/SonataPageBundle/pull/1304
It's probably better to migrate away from the cache bundle to the default Symfony cache in a new major version.

**Pull request closed without merging**
