### PR TITLE
Upgrade to sonata 4

### PR DESCRIPTION
**Pull request by core23**
## Subject

I am targeting this branch, because this is a BC break.

## Changelog

```markdown
### Added
- Add compatiblity with all SonataAdmin 4.0 versions
```

## To do

- [ ] Open block bundle classes for extension
- [x] Require seo-bundle 3

### CODE REVIEW

**Comment by VincentLanglet** [comment]
> * [ ]  Open block bundle classes for extension

Shouldn't we prefer injection/composition instead ?

**Comment by core23** [comment]
I'm not using this bundle anymore.

**Comment by haivala** [comment]
@core23 just out of curiosity: what are you using now for similar tasks?

**Comment by core23** [comment]
Simple symfony controller with custom entities

**Pull request closed without merging**
