### PR TITLE
fixed namespaces for test models

### PR DESCRIPTION
**Pull request by OskarStark**
### Changelog

```markdown
### Fixed
- Fixed namespaces of test models
```

### Subject

The namespaces looks like a copy paste mistake

### CODE REVIEW

**Comment by OskarStark** [comment]
@greg0ire travis is green!

**Comment by OskarStark** [comment]
Isn't there a fixer for this @Soullivaneuh ?

**Comment by Soullivaneuh** [comment]
https://github.com/sonata-project/dev-kit/issues/169

**Comment by Soullivaneuh** [comment]
@OskarStark Fixed namespace for test is pedantic.

**Comment by OskarStark** [comment]
Some time i get it right 💃

**Pull request merged**
