### PR TITLE
3.13.1

### PR DESCRIPTION
**Pull request by greg0ire**

### CODE REVIEW

**Comment by core23** [comment]
Do we need this?

**Comment by greg0ire** [comment]
What do you mean?

**Comment by core23** [comment]
This is a dev dependency. So we do we need a new release?

**Comment by greg0ire** [comment]
Oh right. We don't.

**Comment by OskarStark** [comment]
But if you are using npm install and not, how you should, npm install —production, you end up with this dependency in prod.
So why not just create a release? Doesn’t hurt

**Comment by core23** [comment]
Why would you do this for this *library*? If you call `npm install` on your *project*, you should only load all non-dev dependencies on your project.

**Comment by OskarStark** [comment]
You are right, I mixed things up 😄

**Pull request closed without merging**
