### PR TITLE
Remove twig form themes config

### LINKED ISSUE #1699: Remove Twig form_themes
## Feature Request

After https://github.com/sonata-project/form-extensions/pull/444 gets into a Release,
then this can be removed:
https://github.com/sonata-project/SonataPageBundle/blob/489e2fa48ce170b73e8bebc7ca9c10fac1d7778e/src/DependencyInjection/SonataPageExtension.php#L35-L45

This should be BC, and with a notice to remove the method and `implements PrependExtensionInterface` NEXT_MAJOR

### PR DESCRIPTION
**Pull request by Hanmac**
## Subject

I am targeting this branch, because its BC.

Closes #1699.

## Changelog

```markdown
### Removed
- Removed twig form themes from SonataPageExtension
```

### CODE REVIEW

**Comment by Hanmac** [comment]
hm i need to check what is wrong with the tests, normally PageBundle should have defined the values

**Review by jordisala1991 — APPROVED** [review]

**Comment by Hanmac** [comment]
as for more tests, I'm going to add more tests soon to form-extensions to check that twig theme definitions

**Comment by VincentLanglet** [comment]
> as for more tests, I'm going to add more tests soon to form-extensions to check that twig theme definitions

You mean in this Pr or another ?

**Comment by Hanmac** [comment]
> > as for more tests, I'm going to add more tests soon to form-extensions to check that twig theme definitions
> 
> You mean in this Pr or another ?

different project

i noticed that there are some Tests missing in the [form-extensions](https://github.com/sonata-project/form-extensions) project
(like using MockObject for Twig Extension to see if the config gets extended)
and i would add the test case later there



as for the test in this project, i only found this https://github.com/sonata-project/SonataUserBundle/issues/924 and https://github.com/sonata-project/SonataUserBundle/pull/925
when searching `twig.form.resources` but i don't know how to fix the test for the page bundle so i removed it

similar tests like in https://github.com/sonata-project/SonataUserBundle/pull/925 will be later added into [form-extensions](https://github.com/sonata-project/form-extensions)

**Review by VincentLanglet — APPROVED** [review]

**Comment by VincentLanglet** [comment]
Thanks

**Pull request merged**
