### PR TITLE
Updated German translation

### PR DESCRIPTION
**Pull request by core23**
@OskarStark What do you think?

### CODE REVIEW

**Comment by OskarStark** [comment]
hmm, i think layout is a bit missleading, but i don't like composer, too because its an english word... :smile: 

``Layout-Block-Editor`` ?

**Comment by core23** [comment]
IMO ``Layout-Block-Editor`` seems too much technical. Maybe only ``Editor`` which comes near to the word ``composer``?

**Comment by OskarStark** [comment]
Editor is :+1:

Am Dienstag, 17. November 2015 schrieb Christian Gripp :

**Comment by core23** [comment]
RTM @OskarStark

**Comment by OskarStark** [comment]
Thank you @core23

**Pull request merged**
