### PR TITLE
UI: Show modal dialog in page composer

### PR DESCRIPTION
**Pull request by core23**
Replaces the inline confirm request with a modal dialog.

Before:
bildschirmfoto 2016-01-16 um 22 40 27

After:
bildschirmfoto 2016-01-16 um 22 32 08

### CODE REVIEW

**Comment by OskarStark** [comment]
@core23, can you please check the travis build?

**Comment by core23** [comment]
There is something wrong with travis... This is not related to this PR, see some recent merged commits.

**Comment by OskarStark** [comment]
Thank you @core23

**Comment by rande** [comment]
Are you sure it is an improvement ?

**Comment by core23** [comment]
The problem with the old implementation is, that the confirm panel is hard to handle. If you hover over an other item the question and button are hidden. 

IMO it also looks crap

**Pull request merged**
