### PR TITLE
Use https for doctrine xml xsd

### PR DESCRIPTION
**Pull request by jordisala1991**
Should be pedantic.

### CODE REVIEW

**Comment by jordisala1991** [comment]
Do you know why the build fails here and not on the admin-bundle? @VincentLanglet

**Comment by VincentLanglet** [comment]
> Do you know why the build fails here and not on the admin-bundle? @VincentLanglet

No idea and I don't understand the relation with `Symfony\Component\ErrorHandler\DebugClassLoader`.

**Comment by VincentLanglet** [comment]
So... you did nothing and now it works ?

**Review by VincentLanglet — APPROVED** [review]

**Comment by jordisala1991** [comment]
I dont understand either 🤷‍♂️ 🫠

**Pull request merged**
