### PR TITLE
DevKit updates for 3.x branch

### PR DESCRIPTION
**Pull request by SonataCI**

### CODE REVIEW

**Comment by VincentLanglet** [comment]
We have a probleme here @jordisala1991 ^^'

**Comment by jordisala1991** [comment]
A big, ugly and problematic merge with tons of conflicts? Just break it and I will do the merge tomorrow.

**Comment by VincentLanglet** [comment]
> A big, ugly and problematic merge with tons of conflicts? Just break it and I will do the merge tomorrow.

Indeed the merge will be ugly, but first, we cannot use the config from dev-kit since it cannot install the latest version of php-cs-fixer.

We might remove the update of the php-cs-fixer config for SonataPage 3.x branch.

**Comment by jordisala1991** [comment]
I see 2 options:

1. Ignore php cs fixer failing on this branch.
2. Add this new config conditionally if not on page bundle 3.x otherwise revert to older config.

**Comment by VincentLanglet** [comment]
> I see 2 options:
> 
> 1. Ignore php cs fixer failing on this branch.
> 2. Add this new config conditionally if not on page bundle 3.x otherwise revert to older config.

I'm ok ignoring this, this avoid extra work

**Pull request merged**
