### PR TITLE
Composer: Translated block name and icon

### PR DESCRIPTION
**Pull request by core23**
Added block service icon and translated name.

bildschirmfoto 2015-11-11 um 18 18 42

### CODE REVIEW

**Comment by OskarStark** [comment]
Do we have a test for this somewhere?

**Comment by core23** [comment]
Travis is building green. So there should be no front end tests for this

**Comment by OskarStark** [comment]
yes, but you introduced the icon, so we have to be sure that this will be rendered correctly, and therefore we need a test IMO

**Comment by rande** [comment]
@OskarStark this test need to be done on the sandbox with an ajax call. There is not functionnal tests inside a bundle.

So this PR is ready to merge

**Comment by OskarStark** [comment]
Thank you

**Pull request merged**
