### PR TITLE
Remove duplicated extending instructions, fix symfony cmf router config

### PR DESCRIPTION
**Pull request by sagikazarmark**

### CODE REVIEW

**Comment by core23** [comment]
Can you make travis green?

**Comment by OskarStark** [comment]
@sagikazarmark can you please resubmit this against 3.x ?

**Comment by sagikazarmark** [comment]
Sure, thanks for notification

**Comment by sagikazarmark** [comment]
Hm, it seems this is already done. Can you confirm?

**Comment by OskarStark** [comment]
> Hm, it seems this is already done. Can you confirm?

do you have a link?

**Comment by sagikazarmark** [comment]
https://github.com/sonata-project/SonataPageBundle/blob/3.x/Resources/doc/reference/installation.rst
https://sonata-project.org/bundles/page/master/doc/reference/installation.html

**Comment by OskarStark** [comment]
You are right, this looks ok to me

**Pull request closed without merging**
