### PR TITLE
Added new BlockService to list all pages

### PR DESCRIPTION
**Pull request by core23**
This block could help you on your admin dashboard to show all content pages. It could also been used for displaying a conent list in the frontend.

bildschirmfoto 2015-11-21 um 08 52 36

### CODE REVIEW

**Comment by OskarStark** [comment]
could you please add some screenshots?

can you explain the use case to me? is it for backend or frontend side?

**Comment by OskarStark** [comment]
and a test would be awesome :+1:

**Comment by core23** [comment]
Added a test

**Comment by OskarStark** [comment]
Thank you @core23 

Awesome work :+1:

**Pull request merged**
