### PR TITLE
Fix block admin controller

### PR DESCRIPTION
**Pull request by qsomazzi**

### CODE REVIEW

**Comment by OskarStark** [comment]
thank you @qsomazzi 

can you please describe the bug and the fix a little bite more?

**Comment by qsomazzi** [comment]
Yeah of course, 

This quick fix goal is to handle the right parameter when you switch a block to another parent.

Before : 
We check if the block exist, then get the parent, and re-check is the block exist
After:
We check if the block exist, then get the parent, then check is the parent exist

**Comment by OskarStark** [comment]
ping @Soullivaneuh @rande

**Comment by qsomazzi** [comment]
@rande can you merge it ? it's a really small fix :)

**Pull request merged**
