### PR TITLE
add constraint for host field fix #491

### PR DESCRIPTION
**Pull request by symfou**
I am targetting this branch, because it's a patch.

Closes #491 
Fixes #491 

## Changelog

```markdown
### Fixed
 - Failed to create object: AppBundle\Entity\Site
```

## Subject

Add necessary constraint

### CODE REVIEW

**Comment by core23** [comment]
Please squash your commits

**Comment by qsomazzi** [comment]
Hello @sonata-project/contributors.
I think there was a mistake here, the constraint is set on `Page` entity, or the property host is on `Site`.

This result in a 500 page while trying to edit a page : 
`Property "host" does not exist in class "Sonata\PageBundle\Model\Page"
500 Internal Server Error - ValidatorException`

Can we revert this and make another pr to move the code added ?

**Comment by greg0ire** [comment]
> Can we revert this and make another pr to move the code added ?

Can you make a PR that moves the constraint to the right entity? It will be easier to understand IMO

**Comment by OskarStark** [comment]
I will provide a PR, give me a second

**Comment by OskarStark** [comment]
I created the PR here: https://github.com/sonata-project/SonataPageBundle/pull/736

**Pull request merged**
