### PR TITLE
Move blocks from layout from base_layout

### PR DESCRIPTION
**Pull request by eerison**
## Subject

I am targeting this branch, because {reason}.

Closes #{put_issue_number_here}.

## Changelog

```markdown
### Added
- Added some `Class::newMethod()` to do great stuff.

### Changed

### Deprecated

### Removed

### Fixed

### Security
```

## To do

- [ ] Update the documentation;
- [ ] Add an upgrade note.
- [ ] After the changes is approved, I'll do a commit fixing the indentation

### CODE REVIEW

**Comment by eerison** [comment]
### it's the example how the user should extend the layout.html.twig

file: templates/bundles/SonataPageBundle/layout.html.twig
```twig
{% extends '@SonataPage/base_layout.html.twig' %}

{% block sonata_page_stylesheets %}
    <link rel="stylesheet" href="your.css" media="all">
{% endblock %}

{% block sonata_page_body %}
    <header>
        {{ block('sonata_page_container_header') }}
    </header>

    <section>
        {{ block('sonata_page_container_breadcrumb') }}
    </section>

    {% block sonata_page_container_content_top %}
        {% if page is defined %}
            <section>
                {{ parent() }}
            </section>
        {% endif %}
    {% endblock %}

    <section>
        {{ block('sonata_page_container_content') }}
    </section>


    {% block sonata_page_container_content_bottom %}
        {% if page is defined %}
            <section>
                {{ parent() }}
            </section>
        {% endif %}
    {% endblock %}

    <footer>
        {{ block('sonata_page_container_content_footer') }}
    </footer>
{% endblock %}
```

**Comment by eerison** [comment]
> the user override the layout like this
> 
> file: templates/bundles/SonataPageBundle/layout.html.twig
> 
> ```
> {% extends '@SonataPage/base_layout.html.twig' %}
> 
> {% block sonata_page_stylesheets %}
>     <link rel="stylesheet" href="your.css" media="all">
> {% endblock %}
> 
> {% block sonata_page_body %}
>     <header>
>         {{ block('sonata_page_container_header') }}
>     </header>
> 
>     <section>
>         {{ block('sonata_page_container_breadcrumb') }}
>     </section>
> 
>     {% block sonata_page_container_content_top %}
>         {% if page is defined %}
>             <section>
>                 {{ parent() }}
>             </section>
>         {% endif %}
>     {% endblock %}
> 
>     <section>
>         {{ block('sonata_page_container_content') }}
>     </section>
> 
> 
>     {% block sonata_page_container_content_bottom %}
>         {% if page is defined %}
>             <section>
>                 {{ parent() }}
>             </section>
>         {% endif %}
>     {% endblock %}
> 
>     <footer>
>         {{ block('sonata_page_container_content_footer') }}
>     </footer>
> {% endblock %}
> ```

Hey @jordisala1991  what do you think we move the blocks created into the `layout.html.twig` to `base_laout.html.twig`?

this way I can reuse the code when I'm overriding the `layout.html.twig`

**Comment by jordisala1991** [comment]
IMO we should split PRs. If you are removing deprecated blocks, thats one PR. If you are adding new blocks, thats another PR. To me the only one needed to release is to remove deprecated blocks, but if you want to add more blocks I won't block that PR. (but please, we do separate to see what is new and what is removed better).

**Comment by eerison** [comment]
> IMO we should split PRs. If you are removing deprecated blocks, thats one PR. If you are adding new blocks, thats another PR. To me the only one needed to release is to remove deprecated blocks, but if you want to add more blocks I won't block that PR. (but please, we do separate to see what is new and what is removed better).

Ok, I'll let this PR for this new blocks and after that I rebase with 4.x.

**Comment by eerison** [comment]
This PR is blocked by #1594

**Comment by eerison** [comment]
well, and about this iPR

make sense we overwrite the layout to work like this?  or should we use sonata functions directly into the extended template (in the user side)

**Comment by eerison** [comment]
The main motivation for this PR is the user avoid to implement things like this

```
                    {% if content is defined %}
                        {{ content|raw }}
                    {% else %}
                        {% set content = block('content') is defined ? block('content') : '' %}
                        {% if content|length > 0 %}
                            {{ content|raw }}
                        {% elseif page is defined %}
                            {{ sonata_page_render_container('content', page) }}
                        {% endif %}
                    {% endif %}
```

**Comment by jordisala1991** [comment]
Is this PR a bugfix for 4.x (for a thing that was working on 3.x?), or does this PR breaks BC in a way that it can't be done in a minor?

If any of those 2 question the answer is "Yes", and the PR is simple enough, let's do it, otherwise let's wait after 4.0

**Comment by eerison** [comment]
I'll reopen this PR when I back to work on this ;)

**Pull request closed without merging**
